version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    container_name: esmaster
    environment:
      - node.name=esmaster
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=esmaster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - datamaster:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

volumes:
  datamaster:
    driver: local

networks:
  elastic:
    driver: bridge